### PR TITLE
WIP Add initial work for wave docker connected by a nginx container service

### LINKED ISSUE #6: Error to open the endpoint on web servers

### PR DESCRIPTION
**Pull request by xmnlab**
Closes #6.
This PR aims to add a container for nginx that will proxy the request to the wave container.

### CODE REVIEW

**Comment by esloch** [comment]
Added Dockerfile for NGINX service to solve this:
#### Warning:
``` 
nginx_1    | /docker-entrypoint.sh: Configuration complete; ready for start up
nginx_1    | 2023/03/22 13:18:01 [warn] 1#1: conflicting server name "localhost" on 0.0.0.0:80, ignored
nginx_1    | nginx: [warn] conflicting server name "localhost" on 0.0.0.0:80, ignored
nginx_1    | 2023/03/22 13:18:01 [notice] 1#1: using the "epoll" event method
```

**Comment by xmnlab** [comment]
is this PR supposed to push code to main branch?

**Comment by xmnlab** [comment]
ohw never mind .. this is my own PR  XD

**Comment by xmnlab** [comment]
@esloch thanks for the changes!

**Comment by esloch** [comment]
Ça marche @xmnlab !!!
I added the minimum requirements for the NGINX configuration. 
Can you review this PR? 
Screenshot_20230323_110654

**Comment by xmnlab** [comment]
thanks @esloch !

**Pull request merged**
